// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/route_guide.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AI'ya giden istek (PromptBody karşılığı)
type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartPosition string                 `protobuf:"bytes,4,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition   string                 `protobuf:"bytes,5,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO8601 string (örn: "2024-08-01T00:00:00Z")
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_proto_route_guide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{0}
}

func (x *PromptRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PromptRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PromptRequest) GetStartPosition() string {
	if x != nil {
		return x.StartPosition
	}
	return ""
}

func (x *PromptRequest) GetEndPosition() string {
	if x != nil {
		return x.EndPosition
	}
	return ""
}

func (x *PromptRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *PromptRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// AI'dan dönecek seyahat planı cevabı
type TripPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	DailyPlan     []*DailyPlan           `protobuf:"bytes,2,rep,name=daily_plan,json=dailyPlan,proto3" json:"daily_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripPlanResponse) Reset() {
	*x = TripPlanResponse{}
	mi := &file_proto_route_guide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripPlanResponse) ProtoMessage() {}

func (x *TripPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripPlanResponse.ProtoReflect.Descriptor instead.
func (*TripPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{1}
}

func (x *TripPlanResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *TripPlanResponse) GetDailyPlan() []*DailyPlan {
	if x != nil {
		return x.DailyPlan
	}
	return nil
}

// Trip modelin karşılığı
type Trip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartPosition string                 `protobuf:"bytes,4,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	EndPosition   string                 `protobuf:"bytes,5,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	StartDate     string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TotalDays     int32                  `protobuf:"varint,8,opt,name=total_days,json=totalDays,proto3" json:"total_days,omitempty"`
	RouteSummary  string                 `protobuf:"bytes,9,opt,name=route_summary,json=routeSummary,proto3" json:"route_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_proto_route_guide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{2}
}

func (x *Trip) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Trip) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Trip) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Trip) GetStartPosition() string {
	if x != nil {
		return x.StartPosition
	}
	return ""
}

func (x *Trip) GetEndPosition() string {
	if x != nil {
		return x.EndPosition
	}
	return ""
}

func (x *Trip) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Trip) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Trip) GetTotalDays() int32 {
	if x != nil {
		return x.TotalDays
	}
	return 0
}

func (x *Trip) GetRouteSummary() string {
	if x != nil {
		return x.RouteSummary
	}
	return ""
}

// Günlük plan
type DailyPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyPlan) Reset() {
	*x = DailyPlan{}
	mi := &file_proto_route_guide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPlan) ProtoMessage() {}

func (x *DailyPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPlan.ProtoReflect.Descriptor instead.
func (*DailyPlan) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{3}
}

func (x *DailyPlan) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *DailyPlan) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyPlan) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Kamp alanı konum bilgileri (Location struct'ına birebir uyumlu)
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // optional değil ama boş string olabilir
	SiteUrl       string                 `protobuf:"bytes,3,opt,name=site_url,json=siteUrl,proto3" json:"site_url,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_route_guide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetSiteUrl() string {
	if x != nil {
		return x.SiteUrl
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

var File_proto_route_guide_proto protoreflect.FileDescriptor

const file_proto_route_guide_proto_rawDesc = "" +
	"\n" +
	"\x17proto/route_guide.proto\x12\x05proto\"\xe2\x01\n" +
	"\rPromptRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0estart_position\x18\x04 \x01(\tR\rstartPosition\x12!\n" +
	"\fend_position\x18\x05 \x01(\tR\vendPosition\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\"d\n" +
	"\x10TripPlanResponse\x12\x1f\n" +
	"\x04trip\x18\x01 \x01(\v2\v.proto.TripR\x04trip\x12/\n" +
	"\n" +
	"daily_plan\x18\x02 \x03(\v2\x10.proto.DailyPlanR\tdailyPlan\"\x9d\x02\n" +
	"\x04Trip\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0estart_position\x18\x04 \x01(\tR\rstartPosition\x12!\n" +
	"\fend_position\x18\x05 \x01(\tR\vendPosition\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"total_days\x18\b \x01(\x05R\ttotalDays\x12#\n" +
	"\rroute_summary\x18\t \x01(\tR\frouteSummary\"^\n" +
	"\tDailyPlan\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12+\n" +
	"\blocation\x18\x03 \x01(\v2\x0f.proto.LocationR\blocation\"\xa3\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\bsite_url\x18\x03 \x01(\tR\asiteUrl\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes2J\n" +
	"\tAIService\x12=\n" +
	"\fGeneratePlan\x12\x14.proto.PromptRequest\x1a\x17.proto.TripPlanResponseB%Z#github.com/Semhumc/grpc-proto/protob\x06proto3"

var (
	file_proto_route_guide_proto_rawDescOnce sync.Once
	file_proto_route_guide_proto_rawDescData []byte
)

func file_proto_route_guide_proto_rawDescGZIP() []byte {
	file_proto_route_guide_proto_rawDescOnce.Do(func() {
		file_proto_route_guide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_route_guide_proto_rawDesc), len(file_proto_route_guide_proto_rawDesc)))
	})
	return file_proto_route_guide_proto_rawDescData
}

var file_proto_route_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_route_guide_proto_goTypes = []any{
	(*PromptRequest)(nil),    // 0: proto.PromptRequest
	(*TripPlanResponse)(nil), // 1: proto.TripPlanResponse
	(*Trip)(nil),             // 2: proto.Trip
	(*DailyPlan)(nil),        // 3: proto.DailyPlan
	(*Location)(nil),         // 4: proto.Location
}
var file_proto_route_guide_proto_depIdxs = []int32{
	2, // 0: proto.TripPlanResponse.trip:type_name -> proto.Trip
	3, // 1: proto.TripPlanResponse.daily_plan:type_name -> proto.DailyPlan
	4, // 2: proto.DailyPlan.location:type_name -> proto.Location
	0, // 3: proto.AIService.GeneratePlan:input_type -> proto.PromptRequest
	1, // 4: proto.AIService.GeneratePlan:output_type -> proto.TripPlanResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_route_guide_proto_init() }
func file_proto_route_guide_proto_init() {
	if File_proto_route_guide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_route_guide_proto_rawDesc), len(file_proto_route_guide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_guide_proto_goTypes,
		DependencyIndexes: file_proto_route_guide_proto_depIdxs,
		MessageInfos:      file_proto_route_guide_proto_msgTypes,
	}.Build()
	File_proto_route_guide_proto = out.File
	file_proto_route_guide_proto_goTypes = nil
	file_proto_route_guide_proto_depIdxs = nil
}
