// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/route_guide.proto

package proto

import (
	"context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIRouteService_GenerateRoute_FullMethodName = "/proto.AIRouteService/GenerateRoute"
)

// AIRouteServiceClient is the client API for AIRouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIRouteServiceClient interface {
	GenerateRoute(ctx context.Context, in *GenerateRouteRequest, opts ...grpc.CallOption) (*GenerateRouteResponse, error)
}

type aIRouteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIRouteServiceClient(cc grpc.ClientConnInterface) AIRouteServiceClient {
	return &aIRouteServiceClient{cc}
}

func (c *aIRouteServiceClient) GenerateRoute(ctx context.Context, in *GenerateRouteRequest, opts ...grpc.CallOption) (*GenerateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRouteResponse)
	err := c.cc.Invoke(ctx, AIRouteService_GenerateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIRouteServiceServer is the server API for AIRouteService service.
// All implementations must embed UnimplementedAIRouteServiceServer
// for forward compatibility.
type AIRouteServiceServer interface {
	GenerateRoute(context.Context, *GenerateRouteRequest) (*GenerateRouteResponse, error)
	mustEmbedUnimplementedAIRouteServiceServer()
}

// UnimplementedAIRouteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIRouteServiceServer struct{}

func (UnimplementedAIRouteServiceServer) GenerateRoute(context.Context, *GenerateRouteRequest) (*GenerateRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRoute not implemented")
}
func (UnimplementedAIRouteServiceServer) mustEmbedUnimplementedAIRouteServiceServer() {}
func (UnimplementedAIRouteServiceServer) testEmbeddedByValue()                        {}

// UnsafeAIRouteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIRouteServiceServer will
// result in compilation errors.
type UnsafeAIRouteServiceServer interface {
	mustEmbedUnimplementedAIRouteServiceServer()
}

func RegisterAIRouteServiceServer(s grpc.ServiceRegistrar, srv AIRouteServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIRouteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIRouteService_ServiceDesc, srv)
}

func _AIRouteService_GenerateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIRouteServiceServer).GenerateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIRouteService_GenerateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIRouteServiceServer).GenerateRoute(ctx, req.(*GenerateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIRouteService_ServiceDesc is the grpc.ServiceDesc for AIRouteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIRouteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AIRouteService",
	HandlerType: (*AIRouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRoute",
			Handler:    _AIRouteService_GenerateRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/route_guide.proto",
}
