// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/route_guide.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	StartLocation string                 `protobuf:"bytes,2,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DurationDays  int32                  `protobuf:"varint,4,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	Preferences   []string               `protobuf:"bytes,5,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRouteRequest) Reset() {
	*x = GenerateRouteRequest{}
	mi := &file_proto_route_guide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRouteRequest) ProtoMessage() {}

func (x *GenerateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRouteRequest.ProtoReflect.Descriptor instead.
func (*GenerateRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRouteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GenerateRouteRequest) GetStartLocation() string {
	if x != nil {
		return x.StartLocation
	}
	return ""
}

func (x *GenerateRouteRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *GenerateRouteRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

func (x *GenerateRouteRequest) GetPreferences() []string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type GenerateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripPlanJson  string                 `protobuf:"bytes,1,opt,name=trip_plan_json,json=tripPlanJson,proto3" json:"trip_plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRouteResponse) Reset() {
	*x = GenerateRouteResponse{}
	mi := &file_proto_route_guide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRouteResponse) ProtoMessage() {}

func (x *GenerateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_guide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRouteResponse.ProtoReflect.Descriptor instead.
func (*GenerateRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_guide_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRouteResponse) GetTripPlanJson() string {
	if x != nil {
		return x.TripPlanJson
	}
	return ""
}

var File_proto_route_guide_proto protoreflect.FileDescriptor

const file_proto_route_guide_proto_rawDesc = "" +
	"\n" +
	"\x17proto/route_guide.proto\x12\x05proto\"\xc2\x01\n" +
	"\x14GenerateRouteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12%\n" +
	"\x0estart_location\x18\x02 \x01(\tR\rstartLocation\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12#\n" +
	"\rduration_days\x18\x04 \x01(\x05R\fdurationDays\x12 \n" +
	"\vpreferences\x18\x05 \x03(\tR\vpreferences\"=\n" +
	"\x15GenerateRouteResponse\x12$\n" +
	"\x0etrip_plan_json\x18\x01 \x01(\tR\ftripPlanJson2^\n" +
	"\x0eAIRouteService\x12L\n" +
	"\rGenerateRoute\x12\x1b.proto.GenerateRouteRequest\x1a\x1c.proto.GenerateRouteResponse\"\x00B%Z#github.com/Semhumc/grpc-proto/protob\x06proto3"

var (
	file_proto_route_guide_proto_rawDescOnce sync.Once
	file_proto_route_guide_proto_rawDescData []byte
)

func file_proto_route_guide_proto_rawDescGZIP() []byte {
	file_proto_route_guide_proto_rawDescOnce.Do(func() {
		file_proto_route_guide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_route_guide_proto_rawDesc), len(file_proto_route_guide_proto_rawDesc)))
	})
	return file_proto_route_guide_proto_rawDescData
}

var file_proto_route_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_route_guide_proto_goTypes = []any{
	(*GenerateRouteRequest)(nil),  // 0: proto.GenerateRouteRequest
	(*GenerateRouteResponse)(nil), // 1: proto.GenerateRouteResponse
}
var file_proto_route_guide_proto_depIdxs = []int32{
	0, // 0: proto.AIRouteService.GenerateRoute:input_type -> proto.GenerateRouteRequest
	1, // 1: proto.AIRouteService.GenerateRoute:output_type -> proto.GenerateRouteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_route_guide_proto_init() }
func file_proto_route_guide_proto_init() {
	if File_proto_route_guide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_route_guide_proto_rawDesc), len(file_proto_route_guide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_guide_proto_goTypes,
		DependencyIndexes: file_proto_route_guide_proto_depIdxs,
		MessageInfos:      file_proto_route_guide_proto_msgTypes,
	}.Build()
	File_proto_route_guide_proto = out.File
	file_proto_route_guide_proto_goTypes = nil
	file_proto_route_guide_proto_depIdxs = nil
}
